### ISSUE TITLE
HOW TO: Make CrossBound work with LinuxGSM!

### ISSUE THREAD

**Issue by Mrs-Feathers** [MyristicaFragrans/CrossBound#1]
Hello! Just wanted to share a bit of super amazing awesome stuff here. You can run CrossBound and still have your server managed by linuxgsm! How?

1. Install starbound via LinuxGSM. i'll assume you used the user sbserver for this as thats what it says on the linuxgsm guide for starbound. litterally like 3 commands and you have a fully working starbound server up and running. 
2. with the server stopped, install CrossBound in your /home/sbserver/serverfiles/CrossBound directory. just cd into the serverfiles dir and use git clone command. then cd into CrossBound and run npm install like normal. edit config and all that. run npm start just to make sure its working fine. server path should be like ./../linux/starbound_server on linux.
3.  cd to linux (or wherever the executable is) and make a start.sh or start.bat etc.. this example is for linux but its easy enough to convert to bat if you're running windows 
```#!/bin/bash

# Navigate to the directory where your package.json is located (if needed)
cd /home/sbserver/serverfiles/CrossBound

# Run npm start
npm start```
4. chmod +x the script and make sure its gucci.
5. nano /home/sbserver/lgsm/config-lgsm/sbserver/sbserver.cfg
6. add 
```startparameters=""
executable="./start.sh"``` 
and save.
7. in  /home/sbserver/lgsm/config-lgsm/sbserver/_default.cfg set querymode="1" otherwise its glitchy. basically goes from checking the ports to see if the server is healthy to just making sure the executable is running. so, less great but it gets the monitor command working
8. in linuxgsm guide, add the crontab entries and it should just work fine! test out the monitor command and all that then set it and forget it!

**Comment by MyristicaFragrans** [comment]
Hello! I have uncommitted code that makes Crossbound not handle the server executable, so it will only require read-access to the logs and RCON. I will formalize these changes, which should make integration with systems like LinuxGSM much easier.

**Comment by MyristicaFragrans** [comment]
I have committed the changes in b55edec. You should be able to set up your LinuxGSM server as normal and just point Crossbound to your server's log file and RCON.
I am glad you are getting use out of my program!

**Comment by MyristicaFragrans** [comment]
I assume your issue has been solved. If not, please feel free to re-open this issue.
