### ISSUE TITLE
Problem: CrossBound doesn't see bot text

### ISSUE THREAD

**Issue by Mrs-Feathers** [MyristicaFragrans/CrossBound#2]
Hello! Like many servers, we have bots to connect our server to others. so a user on matrix.furryrefuge.com can still chat with us on discord.furryrefuge.com and so on. the script here only picks up on users and not bots, so while i'm in game i cant see anything anyone said from other servers or if they use a command or something and i feel like that might be a valuable thing to see. i assume if you dont want to see bots, you set it to a channel without bots, but if you're using bots as a chatrelay or time alert tool, listening to music and its showing the next song in text while you're in voice chat, its just plain useful to see bot text as well as normal users.

how can i fix this? or if this is a bug how can i help?

**Comment by MyristicaFragrans** [comment]
Hello! In my testing (which I have upgraded the DiscordJS version since you posted) bots do show up. Bots that use the newer slash commands do not show up correctly (since the response is sent some time after the message is created). I have not tested this with Matrix bots, yet, but I intend to.

**Comment by MyristicaFragrans** [comment]
I assume this has not continued to be an issue.
With regards to slash commands, I do not intend to try to keep track of those. I could not reproduce the issue with regular messages from bots.
Please re-open this issue if it continues to, well, be an issue :smile:
